services:
  - type: web
    name: signalbot-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DEEPSEEK_API_KEY
        value: tu_clave_api_aqui
